### ISSUE TITLE
启动页面报错

### ISSUE THREAD

**Issue by 1696774082** [jiangyuxiaoxiao/Bert-VITS2-UI#4]
<img width="468" alt="捕获" src="https://github.com/jiangyuxiaoxiao/Bert-VITS2-UI/assets/86331716/3bc9b1cf-4f72-44ce-826e-80cb0043f5fc">控制台报错如图，界面空白

**Comment by jiangyuxiaoxiao** [comment]
参考https://www.cnblogs.com/9527l/p/16212940.html并刷新浏览器缓存

**Comment by jiangyuxiaoxiao** [comment]
参考https://www.cnblogs.com/9527l/p/16212940.html
然后刷新浏览器缓存

**Comment by 1696774082** [comment]
已解决，谢谢！
