### ISSUE TITLE
faster here?

### ISSUE THREAD

**Issue by foocker** [jiangyuxiaoxiao/Bert-VITS2-UI#5]
mayebe:[Bert-VITS2-Faster](https://github.com/foocker/Bert-VITS2-Faster )

**Comment by jiangyuxiaoxiao** [comment]
没太明白，这个项目只是个前端界面，推理是后端实现的。

**Comment by foocker** [comment]
> 没太明白，这个项目只是个前端界面，推理是后端实现的。

替换到这个后端，不是就更快了呢？

**Comment by jiangyuxiaoxiao** [comment]
> > 没太明白，这个项目只是个前端界面，推理是后端实现的。
> 
> 替换到这个后端，是不是就更快了呢？

我看这个项目目前并没有api后端，你可以仿照原项目实现相同的接口

**Comment by foocker** [comment]
> > > 没太明白，这个项目只是个前端界面，推理是后端实现的。
> > 
> > 
> > 替换到这个后端，是不是就更快了呢？
> 
> 我看这个项目目前并没有api后端，你可以仿照原项目实现相同的接口

用原装的就行了。我自己的话，用tritonserver。

**Comment by jiangyuxiaoxiao** [comment]
好的，欢迎其他bertVits2的衍生项目也使用hiyori ui。但是有关推理速度的issue与本项目关系不大，所以close了。

**Comment by foocker** [comment]
> 好的，欢迎其他bertVits2的衍生项目也使用hiyori ui。但是有关推理速度的issue与本项目关系不大，所以close了。

这不是issue哦，你完全可以用我的后端，速度更快。只是一个建议而已。是原版的9倍，何乐而不为呢？况且，原版的速度，也无法落地。

**Comment by Stardust-minus** [comment]
> > 好的，欢迎其他bertVits2的衍生项目也使用hiyori ui。但是有关推理速度的issue与本项目关系不大，所以close了。
> 
> 这不是issue哦，你完全可以用上面的后端，速度更快。只是一个建议而已，是原版的9倍，何乐而不为呢？况且，原版的速度，也无法落地。核心的速度达不到，ui的意义就没有了。如果只是玩玩，当没说。

主项目已完成FP16及int8的适配，会在下个版本更新。同时主项目的推理速度已足够快（几十-一两百ms级），个人认为作用不大。
最后，后端有关的问题请在主项目发起Discussion，如果您还想继续探讨，我们可以在那接着聊。
